# Generated by Django 4.2.23 on 2026-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_done', 'first_reminder', 'sent_reminders'], name='idx_reminder_check'),
        ),
    ]
