# Generated by Django 4.2.23 on 2026-07-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_category_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
