# Generated by Django 4.2.23 on 2026-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_cycle_generated',
            field=models.BooleanField(default=False),
        ),
    ]
